sudo: required
language: java
jdk:
- oraclejdk8
before_script:
- sudo apt-get -qq update
- sudo apt-get install ant-optional -y
- sudo add-apt-repository ppa:eyecreate/haxe -y
- sudo apt-get update
- sudo apt-get install haxe -y
- mkdir ~/haxelib
- haxelib setup ~/haxelib
- haxelib install hxjava
- haxelib git debugger https://github.com/TiVo/debugger.git
- mkdir build
- mkdir report
script: make ANT_TARGET=$ANT_TARGET test
env:
    - IDEA_VERSION=2016.3.7 ANT_TARGET=test
    - IDEA_VERSION=2017.2.6 ANT_TARGET=test
    - IDEA_VERSION=2017.3.6 ANT_TARGET=test

notifications:
  email: false
